name: Deploy Functions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - name: User el secreto y mostrarlo (solo para prueba)
      env:
        TICK_SECRET: ${{ secrets.TICK_SECRET }}
      run: echo "El secreto es: $TICK_SECRET"